services:
  db:
    image: postgres:13-alpine
    container_name: postgres13
    hostname: postgres13
    env_file:
      - .env
    command: >
      postgres -c wal_level=replica -c archive_mode=on -c archive_timeout=60s -c archive_command='test ! -f /wal_archive/%f && cp %p /wal_archive/%f'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/backups:/backups
      - ./db/wal_archive:/wal_archive
    ports:
      - "5432:5432"
    networks:
      pgnet:
        ipv4_address: 172.28.0.10
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer
    hostname: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: 172.28.0.10
    networks:
      pgnet:
        ipv4_address: 172.28.0.11
    restart: unless-stopped

networks:
  pgnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
