version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres132
    hostname: postgres13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/backups:/backups
    ports:
      - "5432:5432"
    networks:
      pgnet:
        ipv4_address: 172.29.0.10
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer2
    hostname: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: 172.29.0.10
    networks:
      pgnet:
        ipv4_address: 172.29.0.11
    restart: unless-stopped

networks:
  pgnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.0.1
